### ISSUE TITLE
Crash during UpdateSubscription

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/fiware-orion#3701]
Version: `2.4.1_20200923174553 git_hash f416ddb73b090c9bc21313d19f5cada7f51744ee`

On PRO environment crash and core generation at September 29th, 17:22:55. Backtrace:

```
(gdb) bt
#0  0x00007f9bba4f34f3 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib64/libstdc++.so.6
#1  0x00000000005e8acc in mongoUpdateSubscription(ngsiv2::SubscriptionUpdate const&, OrionError*, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool const&, ApiVersion) ()
#2  0x00000000004f578a in patchSubscription(ConnectionInfo*, int, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, ParseData*) ()
#3  0x000000000050fa25 in ?? ()
#4  0x00000000005107df in orion::requestServe(ConnectionInfo*) ()
#5  0x000000000050b956 in ?? ()
#6  0x0000000000672d89 in ?? ()
#7  0x0000000000673b20 in ?? ()
#8  0x00000000006782e8 in ?? ()
#9  0x00007f9bbb447aa1 in start_thread () from /lib64/libpthread.so.0
#10 0x00007f9bb9d10c4d in clone () from /lib64/libc.so.6
```

**Comment by fgalan** [comment]
Do you have the update request that supposedly caused the crash?

**Comment by cesarjorgemartinez** [comment]
I don't have the update but has occurred when a subscription has been activated and it was in the first subscription
